[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production.variables]
NODE_ENV = "production"
JAVA_TOOL_OPTIONS = "-Xms256m -Xmx1024m -XX:+UseG1GC -XX:+UseStringDeduplication"

[environments.staging.variables]
NODE_ENV = "staging"
JAVA_TOOL_OPTIONS = "-Xms128m -Xmx512m -XX:+UseG1GC"
